version: '3'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - APP_DB_USER=docker
#      - APP_DB_PASS=docker
#      - APP_DB_NAME=EmployeeMS
#    volumes:
#      - ./db/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
    ports:
      - 5431:5432